### ISSUE TITLE
can't match the file dir in pouring dataset 

### ISSUE THREAD

**Issue by zhywanna** [yilundu/nerflow#4]
I feel sorry to bother you again. I just finish the first phase of training with your sincerely help and move on to the next command which is `python run_nerf.py --config=configs/pour_baseline_flow.txt` and got `FileNotFoundError: No such file: '/nerflow/data/nerf_synthetic/pouring_dataset/depth_train/r_1_flow0068.hdr'`.
I look into transforms_train.json and find out that item "depth_train_path" seems give the filename that doesn't match with the filename in depth_train folder actually. I just add some screenshot in case I didn't describe the problem clearly.
![image](https://user-images.githubusercontent.com/47680024/148910567-2dcd0e3d-5638-4ecd-9847-1707ce25013b.png)
![image](https://user-images.githubusercontent.com/47680024/148910689-7759b905-54ba-4e58-b59c-fcdc1d2910b2.png)

**Comment by yilundu** [comment]
Hi, sorry about the above issue -- I am a bit busy with an upcoming conference deadline currently but will push a change later tonight

**Comment by yilundu** [comment]
I just pushed a change -- can you see if it resolves your issue?

**Comment by zhywanna** [comment]
the error is still the same, `r_1_flow0068.hdr`doesn't exist in "pouring_dataset/depth_train/" while that dir has `r_1_flow0113.hdr`instead.
![image](https://user-images.githubusercontent.com/47680024/149273845-8318e841-09aa-4775-8dd7-4b461d9158ed.png)
![image](https://user-images.githubusercontent.com/47680024/149273747-cf307756-6bcf-4b2a-8862-d9006639c987.png)

**Comment by zhywanna** [comment]
It really work! Could you tell me why? Thanks.

**Comment by zhywanna** [comment]
but another error occurred 
![image](https://user-images.githubusercontent.com/47680024/149293500-0fbc3d58-bd45-4a00-9f68-36dea2dfe4b9.png)

**Comment by zhywanna** [comment]
Yes and I just finished under the installation and try it again, but nothing changed.

**Comment by yilundu** [comment]
What happens when you print torchdiffeq.__file__? Can you check that it is using the version of the torchdiffeq library in the lib folder?

**Comment by zih1998** [comment]
> I feel sorry to bother you again. I just finish the first phase of training with your sincerely help and move on to the next command which is `python run_nerf.py --config=configs/pour_baseline_flow.txt` and got `FileNotFoundError: No such file: '/nerflow/data/nerf_synthetic/pouring_dataset/depth_train/r_1_flow0068.hdr'`. I look into transforms_train.json and find out that item "depth_train_path" seems give the filename that doesn't match with the filename in depth_train folder actually. I just add some screenshot in case I didn't describe the problem clearly. ![image](https://user-

Excuse me, have you encountered this problem when running the project? Also are you using the same version of cuda and pytorch as the author?
![image](https://user-images.githubusercontent.com/45114368/170425058-065df04d-2a0f-4bd8-b282-6d9f9225d73d.png)

**Comment by yilundu** [comment]
The above error might be due to having two different LPIP directories installed in python -- you can delete the lpip folder in this directory.

**Comment by zih1998** [comment]
> The above error might be due to having two different LPIP directories installed in python -- you can delete the lpip folder in this directory.

When I delete it shows "ModuleNotFoundError: No module named 'lpip'  ".
 
![image](https://user-images.githubusercontent.com/45114368/170426762-b4c98b1d-7f13-4e49-ba3f-582682594124.png)

**Comment by zih1998** [comment]
> > The above error might be due to having two different LPIP directories installed in python -- you can delete the lpip folder in this directory.
> 
> When I delete it shows "ModuleNotFoundError: No module named 'lpip' ".
> 
And my test environment is torch1.10+cuda111 ubuntu20.04, I don't know if this will affect the operation.

**Comment by zih1998** [comment]
Can you share the information about the dependent libraries of each version in your configuration environment? I configured according to requirement.txt and found that some libraries did not match.

**Comment by yilundu** [comment]
Sure, here is a full list of libraries in my pip folder:

```
absl-py @ file:///tmp/build/80754af9/absl-py_1600297527605/work
addict==2.4.0
aiohttp @ file:///tmp/build/80754af9/aiohttp_1602530305083/work
-e git+https://github.com/Improbable-AI/airobot.git@4cef868ed7ab1c8ecd3f63b1290b5f1202bebda3#egg=airobot
alabaster==0.7.12
antlr4-python3-runtime==4.8
anyio==3.3.0
appdirs==1.4.4
argon2-cffi==20.1.0
assimp==4.1.4
astroid==2.11.2
astropy==4.3.1
asttokens==2.0.5
astunparse==1.6.3
async-generator==1.10
async-timeout==3.0.1
atari-py==0.2.9
attrs==21.2.0
autopep8==1.6.0
Babel==2.9.1
backcall==0.2.0
baselines==0.1.5
black==21.4b2
bleach==3.3.1
blinker==1.4
brotlipy==0.7.0
cached-property==1.5.2
cachetools @ file:///tmp/build/80754af9/cachetools_1596822027882/work
catkin-pkg==0.4.23
certifi==2020.6.20
cffi==1.12.3
chardet==3.0.4
chess==1.6.1
chex==0.1.1
clang==5.0
click==7.1.2
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1598884132938/work
colorama==0.4.4
colorlog==5.0.1
comet-ml==3.28.2
commonmark==0.9.1
ConfigArgParse==1.1
configobj==5.0.6
contextlib2==21.6.0
coverage==5.5
cryptography @ file:///tmp/build/80754af9/cryptography_1601046817403/work
cssselect2==0.4.1
cvxpy==1.1.15
cycler==0.10.0
Cython==0.29.24
cytoolz==0.11.0
dask @ file:///tmp/build/80754af9/dask-core_1602083700509/work
debugpy==1.4.1
decorator==4.4.2
defusedxml==0.7.1
deprecation==2.1.0
detectron2==0.6+cu101
-e git+git@github.com:jannerm/denoising-diffusion.git@9b3435ccefe6a7e7ae89ce276a0c019b6d6c64e4#egg=diffusion
dill==0.3.4
distro==1.5.0
dm-haiku==0.0.4
dm-tree==0.1.6
docopt==0.6.2
docutils==0.16
dulwich==0.20.35
easy-to-hard-data==1.0.0
easydict==1.9
ecos==2.0.7.post1
einops==0.3.0
entrypoints==0.3
-e git+git@github.com:anthonysimeonov/eof_robot.git@22b683deda7b8a37da645ed3d2db8687abc0b8ff#egg=eof_robot
evdev==1.4.0
everett==3.0.0
executing==0.8.2
fasteners==0.16.3
flake8==4.0.1
flatbuffers==1.12
freetype-py==2.3.0
future==0.18.2
fvcore==0.1.5.post20211023
gast==0.4.0
gitdb==4.0.7
GitPython==3.1.18
glfw==2.1.0
google-auth @ file:///tmp/build/80754af9/google-auth_1601995530934/work
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
googleapis-common-protos==1.55.0
grpcio==1.39.0
gym==0.18.3
h5py==3.1.0
healpy==1.15.0
hydra-core==1.1.1
icecream==2.1.0
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
imageio==2.8.0
imageio-ffmpeg==0.4.2
imagesize==1.2.0
imgaug==0.4.0
importlib-metadata==3.10.1
importlib-resources==5.4.0
iniconfig==1.1.1
ipykernel @ file:///tmp/build/80754af9/ipykernel_1596206598566/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipython==7.25.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
isort==5.10.1
jax==0.3.2
jaxlib==0.3.2+cuda11.cudnn82
jaxline==0.0.3
jedi @ file:///tmp/build/80754af9/jedi_1596490743326/work
Jinja2==3.0.1
joblib @ file:///tmp/build/80754af9/joblib_1601912903842/work
json5==0.9.6
jsonpickle==1.5.2
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyter-packaging==0.10.4
jupyter-server==1.10.1
jupyterlab==3.0.16
jupyterlab-pygments==0.1.2
jupyterlab-server==2.6.1
jupyterlab-widgets==1.0.0
kaleido==0.2.1
keras==2.6.0
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
lazy-object-proxy==1.7.1
lmdb==1.2.1
lockfile==0.12.2
lxml==4.7.1
Markdown @ file:///tmp/build/80754af9/markdown_1603216490021/work
MarkupSafe==2.0.1
matplotlib==3.2.2
matplotlib-inline==0.1.2
mc-bin-client==1.0.1
mccabe==0.6.1
meshcat==0.2.0
mistune==0.8.4
mkl-fft==1.3.1
mkl-random==1.2.2
mkl-service==2.4.0
ml-collections==0.1.1
mpi4py==3.1.1
mpmath==1.2.1
mujoco-py==2.0.2.13
multidict @ file:///tmp/build/80754af9/multidict_1600456400975/work
munch==2.5.0
mypy-extensions==0.4.3
nbclassic==0.3.1
nbclient==0.5.3
nbconvert==6.1.0
nbformat==5.1.3
-e git+git@github.com:anthonysimeonov/ndf_robot_private.git@d8f22419e4957331d1547fb470ea79b78b3d866b#egg=ndf_robot
nest-asyncio==1.5.1
networkx @ file:///tmp/build/80754af9/networkx_1598376031484/work
notebook==6.4.0
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1634106693478/work
numpyro==0.8.0
nvidia-ml-py3==7.352.0
oauthlib==3.1.0
olefile==0.46
omegaconf==2.1.1
opencv-python==4.5.3.56
opt-einsum==3.3.0
optax==0.0.9
ordered-set==4.0.2
osqp==0.6.2.post0
packaging==21.0
pandas @ file:///tmp/build/80754af9/pandas_1602088128026/work
pandocfilters==1.4.3
parso==0.7.0
pathspec==0.9.0
-e git+git@github.com:anthonysimeonov/DON_depth.git@9cad6721a94fd41ac959bd147f47ac68a69a9577#egg=pdc
-e git+https://github.com/lucidrains/perceiver-pytorch.git@abbb5d5949d3509c57749bd134f5068f2761aac7#egg=perceiver_pytorch
pexpect @ file:///tmp/build/80754af9/pexpect_1594383317248/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1594384075987/work
Pillow==8.3.2
pipreqs==0.4.11
platformdirs==2.5.2
plotly==5.2.1
pluggy==0.13.1
plyfile==0.7.4
pockets==0.9.1
pointnet2==0.0.0
portalocker==2.3.2
progressbar2==3.53.1
prometheus-client==0.11.0
promise==2.3
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1602688806899/work
protobuf==3.13.0
psutil==5.8.0
ptyprocess==0.6.0
py==1.10.0
py-cpuinfo==8.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyassimp==4.1.4
pybullet==3.1.3
pycocotools==2.0.2
pycodestyle==2.8.0
pycollada==0.6
pycparser==2.19
pydot==1.4.2
pyerfa==2.0.0
pyflakes==2.4.0
pygame==2.0.1
pyglet==1.5.15
Pygments==2.9.0
PyJWT==1.7.1
pylint==2.13.5
pymap3d==2.7.0
PyMCubes==0.1.2
pymunk==5.5.0
pyngrok==5.0.6
pynput==1.7.3
PyOpenGL==3.1.0
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1594392929924/work
pyparsing==2.4.7
pypcd==0.1.1
pyrender==0.1.45
pyrsistent==0.18.1
PySocks @ file:///tmp/build/80754af9/pysocks_1594394576006/work
pytest==6.2.4
pytest-cov==2.12.1
pytest-html==3.1.1
pytest-lazy-fixture==0.6.3
pytest-metadata==1.11.0
python-dateutil==2.8.1
python-lzf==0.2.4
python-utils==2.5.6
python-xlib==0.31
pytz==2021.1
PyWavelets @ file:///tmp/build/80754af9/pywavelets_1601658308664/work
PyYAML==5.3.1
pyzmq==22.1.0
qdldl==0.1.5.post0
recommonmark==0.7.1
regex==2021.11.2
reportlab==3.5.68
requests @ file:///tmp/build/80754af9/requests_1592841827918/work
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
requests-unixsocket==0.2.0
retrying==1.3.3
rospkg==1.3.0
rsa @ file:///tmp/build/80754af9/rsa_1596998415516/work
Rtree==0.9.7
ruamel.yaml==0.17.10
ruamel.yaml.clib==0.2.6
sacred==0.8.2
scikit-image==0.16.2
scikit-learn @ file:///tmp/build/80754af9/scikit-learn_1598376882706/work
scipy @ file:///tmp/build/80754af9/scipy_1641536880743/work
scs==2.1.4
seaborn @ file:///tmp/build/80754af9/seaborn_1600553570093/work
semantic-version==2.9.0
Send2Trash==1.7.1
Shapely==1.7.1
sip==4.19.24
six==1.15.0
slot-attention==1.1.1
smmap==4.0.0
sniffio==1.2.0
snowballstemmer==2.1.0
Sphinx==4.1.1
sphinx-rtd-theme==0.5.2
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-napoleon==0.7
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
stonesoup==0.1b6
svglib==1.1.0
sympy==1.8
tabulate==0.8.9
tap==0.2
tenacity==8.0.1
tensorboard==2.2.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.6.0
tensorflow-addons==0.13.0
tensorflow-datasets==4.3.0
tensorflow-estimator==2.6.0
tensorflow-metadata==1.7.0
tensorflow-probability==0.13.0
termcolor==1.1.0
terminado==0.10.1
testpath==0.5.0
threadpoolctl @ file:///tmp/tmp9twdgx9k/threadpoolctl-2.1.0-py3-none-any.whl
tinycss2==1.1.1
tinydb==4.5.1
toml==0.10.2
tomli==2.0.1
tomlkit==0.7.2
toolz @ file:///tmp/build/80754af9/toolz_1601054250827/work
torch==1.11.0
torch-ema @ git+https://github.com/fadel/pytorch_ema@3985995e523aa25dd3cff7e7984130eef90a4282
torchaudio==0.11.0
-e git+git@github.com:yilundu/dynamic_nerf.git@1d6a93372eb01c7692f94673494c632e3d0576f3#egg=torchdiffeq&subdirectory=lib/torchdiffeq
torchmeta==1.8.0
torchsearchsorted==1.1
torchvision==0.4.0
tornado==6.1
tqdm==4.60.0
traitlets @ file:///tmp/build/80754af9/traitlets_1602787416690/work
transforms3d==0.3.1
trimesh==3.9.32
typed-ast==1.4.3
typeguard==2.13.3
typing-extensions==4.2.0
u-msgpack-python==2.7.1
urdfpy==0.0.22
urllib3 @ file:///tmp/build/80754af9/urllib3_1603305693037/work
utm==0.7.0
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
websocket-client==1.1.0
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
wurlitzer==3.0.2
xxhash==2.0.2
yacs==0.1.8
yarg==0.1.9
yarl @ file:///tmp/build/80754af9/yarl_1602693045341/work
zipp==3.5.0
zmq==0.0.0
```

**Comment by zih1998** [comment]
> Sure, here is a full list of libraries in my pip folder:
Thanks！Could you please execute this command ' pip list --format=freeze > requirements.txt ', because the file generated in the above way is suitable for your personal local system.

**Comment by yilundu** [comment]
Sure! Here is the output I get:

```
-illow==8.3.1
absl-py==0.10.0
addict==2.4.0
aiohttp==3.6.3
airobot==0.1
alabaster==0.7.12
antlr4-python3-runtime==4.8
anyio==3.3.0
appdirs==1.4.4
argon2-cffi==20.1.0
assimp==4.1.4
astroid==2.11.2
astropy==4.3.1
asttokens==2.0.5
astunparse==1.6.3
async-generator==1.10
async-timeout==3.0.1
atari-py==0.2.9
attrs==21.2.0
autopep8==1.6.0
Babel==2.9.1
backcall==0.2.0
baselines==0.1.5
black==21.4b2
bleach==3.3.1
blinker==1.4
brotlipy==0.7.0
cached-property==1.5.2
cachetools==4.1.1
catkin-pkg==0.4.23
certifi==2020.6.20
cffi==1.12.3
chardet==3.0.4
chess==1.6.1
chex==0.1.1
clang==5.0
click==7.1.2
cloudpickle==1.6.0
colorama==0.4.4
colorlog==5.0.1
comet-ml==3.28.2
commonmark==0.9.1
ConfigArgParse==1.1
configobj==5.0.6
contextlib2==21.6.0
coverage==5.5
cryptography==3.1.1
cssselect2==0.4.1
cvxpy==1.1.15
cycler==0.10.0
Cython==0.29.24
cytoolz==0.11.0
dask==2.30.0
debugpy==1.4.1
decorator==4.4.2
defusedxml==0.7.1
deprecation==2.1.0
detectron2==0.6+cu101
diffusion==0.0.0
dill==0.3.4
distro==1.5.0
dm-haiku==0.0.4
dm-tree==0.1.6
docopt==0.6.2
docutils==0.16
dulwich==0.20.35
easy-to-hard-data==1.0.0
easydict==1.9
ecos==2.0.7.post1
einops==0.3.0
entrypoints==0.3
eof-robot==0.0.0
evdev==1.4.0
everett==3.0.0
executing==0.8.2
fasteners==0.16.3
flake8==4.0.1
flatbuffers==1.12
freetype-py==2.3.0
future==0.18.2
fvcore==0.1.5.post20211023
gast==0.4.0
gitdb==4.0.7
GitPython==3.1.18
glfw==2.1.0
google-auth==1.22.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
googleapis-common-protos==1.55.0
grpcio==1.39.0
gym==0.18.3
h5py==3.1.0
healpy==1.15.0
hydra-core==1.1.1
icecream==2.1.0
idna==2.10
imageio==2.8.0
imageio-ffmpeg==0.4.2
imagesize==1.2.0
imgaug==0.4.0
importlib-metadata==3.10.1
importlib-resources==5.4.0
iniconfig==1.1.1
ipykernel==5.3.4
ipython==7.25.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
isort==5.10.1
jax==0.3.2
jaxlib==0.3.2+cuda11.cudnn82
jaxline==0.0.3
jedi==0.17.2
Jinja2==3.0.1
joblib==0.17.0
json5==0.9.6
jsonpickle==1.5.2
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyter-packaging==0.10.4
jupyter-server==1.10.1
jupyterlab==3.0.16
jupyterlab-pygments==0.1.2
jupyterlab-server==2.6.1
jupyterlab-widgets==1.0.0
kaleido==0.2.1
keras==2.6.0
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
lazy-object-proxy==1.7.1
lmdb==1.2.1
lockfile==0.12.2
lxml==4.7.1
Markdown==3.3.2
MarkupSafe==2.0.1
matplotlib==3.2.2
matplotlib-inline==0.1.2
mc-bin-client==1.0.1
mccabe==0.6.1
meshcat==0.2.0
mistune==0.8.4
mkl-fft==1.3.1
mkl-random==1.2.2
mkl-service==2.4.0
ml-collections==0.1.1
mpi4py==3.1.1
mpmath==1.2.1
mujoco-py==2.0.2.13
multidict==4.7.6
munch==2.5.0
mypy-extensions==0.4.3
nbclassic==0.3.1
nbclient==0.5.3
nbconvert==6.1.0
nbformat==5.1.3
ndf-robot==0.0.0
nest-asyncio==1.5.1
networkx==2.5
notebook==6.4.0
numpy==1.21.2
numpyro==0.8.0
nvidia-ml-py3==7.352.0
oauthlib==3.1.0
olefile==0.46
omegaconf==2.1.1
opencv-python==4.5.3.56
opt-einsum==3.3.0
optax==0.0.9
ordered-set==4.0.2
osqp==0.6.2.post0
packaging==21.0
pandas==1.1.3
pandocfilters==1.4.3
parso==0.7.0
pathspec==0.9.0
pdc==0.0.1
perceiver-pytorch==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.3.2
pip==20.2.4
pipreqs==0.4.11
platformdirs==2.5.2
plotly==5.2.1
pluggy==0.13.1
plyfile==0.7.4
pockets==0.9.1
pointnet2==0.0.0
portalocker==2.3.2
progressbar2==3.53.1
prometheus-client==0.11.0
promise==2.3
prompt-toolkit==3.0.8
protobuf==3.13.0
psutil==5.8.0
ptyprocess==0.6.0
py==1.10.0
py-cpuinfo==8.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyassimp==4.1.4
pybullet==3.1.3
pycocotools==2.0.2
pycodestyle==2.8.0
pycollada==0.6
pycparser==2.19
pydot==1.4.2
pyerfa==2.0.0
pyflakes==2.4.0
pygame==2.0.1
pyglet==1.5.15
Pygments==2.9.0
PyJWT==1.7.1
pylint==2.13.5
pymap3d==2.7.0
PyMCubes==0.1.2
pymunk==5.5.0
pyngrok==5.0.6
pynput==1.7.3
PyOpenGL==3.1.0
pyOpenSSL==19.1.0
pyparsing==2.4.7
pypcd==0.1.1
pyrender==0.1.45
pyrsistent==0.18.1
PySocks==1.7.1
pytest==6.2.4
pytest-cov==2.12.1
pytest-html==3.1.1
pytest-lazy-fixture==0.6.3
pytest-metadata==1.11.0
python-dateutil==2.8.1
python-lzf==0.2.4
python-utils==2.5.6
python-xlib==0.31
pytz==2021.1
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==22.1.0
qdldl==0.1.5.post0
recommonmark==0.7.1
regex==2021.11.2
reportlab==3.5.68
requests==2.24.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
requests-unixsocket==0.2.0
retrying==1.3.3
rospkg==1.3.0
rsa==4.6
Rtree==0.9.7
ruamel.yaml==0.17.10
ruamel.yaml.clib==0.2.6
sacred==0.8.2
scikit-image==0.16.2
scikit-learn==0.23.2
scipy==1.7.3
scs==2.1.4
seaborn==0.11.0
semantic-version==2.9.0
Send2Trash==1.7.1
setuptools==50.3.0.post20201006
Shapely==1.7.1
sip==4.19.24
six==1.15.0
slot-attention==1.1.1
smmap==4.0.0
sniffio==1.2.0
snowballstemmer==2.1.0
Sphinx==4.1.1
sphinx-rtd-theme==0.5.2
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-napoleon==0.7
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
stonesoup==0.1b6
svglib==1.1.0
sympy==1.8
tabulate==0.8.9
tap==0.2
tenacity==8.0.1
tensorboard==2.2.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.6.0
tensorflow-addons==0.13.0
tensorflow-datasets==4.3.0
tensorflow-estimator==2.6.0
tensorflow-metadata==1.7.0
tensorflow-probability==0.13.0
termcolor==1.1.0
terminado==0.10.1
testpath==0.5.0
threadpoolctl==2.1.0
tinycss2==1.1.1
tinydb==4.5.1
toml==0.10.2
tomli==2.0.1
tomlkit==0.7.2
toolz==0.11.1
torch==1.11.0
torch-ema==0.2
torchaudio==0.11.0
torchdiffeq==0.0.1
torchmeta==1.8.0
torchsearchsorted==1.1
torchvision==0.4.0
tornado==6.1
tqdm==4.60.0
traitlets==5.0.5
transforms3d==0.3.1
trimesh==3.9.32
typed-ast==1.4.3
typeguard==2.13.3
typing-extensions==4.2.0
u-msgpack-python==2.7.1
urdfpy==0.0.22
urllib3==1.25.11
utm==0.7.0
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.1.0
Werkzeug==1.0.1
wheel==0.36.2
widgetsnbextension==3.5.1
wrapt==1.12.1
wurlitzer==3.0.2
xxhash==2.0.2
yacs==0.1.8
yarg==0.1.9
yarl==1.6.2
zipp==3.5.0
zmq==0.0.0
```

**Comment by hmppt** [comment]
> but another error occurred ![image](https://user-images.githubusercontent.com/47680024/149293500-0fbc3d58-bd45-4a00-9f68-36dea2dfe4b9.png)
Have you resolved this situation? I also encountered the same problem.

**Comment by yilundu** [comment]
Yes, you need to install the neuralODE library included in the repo: https://github.com/yilundu/nerflow/tree/main/lib/torchdiffeq

**Comment by hmppt** [comment]
> 是的，您需要安装 repo 中包含的 neuralODE 库： https: [//github.com/yilundu/nerflow/tree/main/lib/torchdiffeq](https://github.com/yilundu/nerflow/tree/main/lib/torchdiffeq)
Thanks for the quick response. But it still doesn't work, because odeint_adjoint() does not receive the f_options parameter, I observed that odeint_adjoint() in ../lib/torchdiffeq/torchdiffeq/_impl/odeint.py accepts the f_options parameter, so I made the code as follows changed and it worked successfully.

![image](https://user-images.githubusercontent.com/43752397/224724764-9d44fdfb-1a50-4a3b-836d-8dd203867995.png)
